blog/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from baton.autodiscover import admin
from datetime import datetime, timedelta, date

from blog_page.models import Blog
from .settings import MEDIA_URL, MEDIA_ROOT
from user.views import RegisterView, LoginView, logout
from blog_page.views import (
    HomePage,
    BlogWrite, IndexView, MyBlogList, BlogDetail, BlogList, RelationCreateView, FollowerBlogView
)

orig_index = admin.site.index
def blog_index(request, extra_context=None):
    base_date = datetime.now() - timedelta(days=6)
    blog_data = {}
    for i in range(7):
        target_dttm = base_date + timedelta(days=i)
        date_key = target_dttm.strftime("%Y-%m-%d")
        target_date = date(target_dttm.year, target_dttm.month, target_dttm.day)
        blog_cnt = Blog.objects.filter(registered_date__date=target_date).count()
        blog_data[date_key] = blog_cnt
    print(blog_data)
    extra_context = {
        'blogs': blog_data
    }
    return orig_index(request, extra_context)

admin.site.index = blog_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baton/', include('baton.urls')),
    path('recent-blog/', IndexView.as_view()),
    path('', HomePage.as_view()),
    path('logout/', logout, name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('blog/write/', BlogWrite.as_view(), name='blog_write'),
    path('blog/detail/<int:pk>/', BlogDetail.as_view(), name='blog_detail'),
    path('myblog/<str:writer>/', BlogList.as_view(), name='blog_list'),
    path('myblog/', MyBlogList.as_view(), name='myblog'),
    path('follow/', RelationCreateView.as_view()),
    path('blog/follower/', FollowerBlogView.as_view()),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

blog_page/models.py
from django.db import models
from datetime import datetime
# Create your models here.

def upload_to(instance, filename):
    if filename == 'blank.png':
        return 'blank.png'
    return 'images/%s/%s' % (instance.writer.username, filename)

class Blog(models.Model):
    title = models.CharField(max_length=255, verbose_name='제목')
    contents = models.TextField(verbose_name='내용')
    thumbnails = models.ImageField(blank=True,upload_to=upload_to,null=True,default='blank.png')
    writer = models.ForeignKey('user.User',on_delete=models.CASCADE,verbose_name='작성자')
    tags = models.ManyToManyField('tag.Tag',verbose_name='태그')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')


    def __str__(self):
        return self.title

    class Meta:
        db_table = 'blog'
        verbose_name = '게시글'
        verbose_name_plural = '게시글'

blog_page/forms.py
from django import forms

class BlogForm(forms.Form):
    title = forms.CharField(max_length=255, label='제목', error_messages={'required':'제목을 입력해주세요'})
    contents = forms.CharField(widget=forms.Textarea, label='내용', error_messages={'required':'내용을 입력해주세요.'})
    tags = forms.CharField(label='태그',required=False)
    image = forms.ImageField(label='썸네일',required=False)

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        contents = cleaned_data.get('contents')

        if not title:
            self.add_error('title','제목을 입력해주세요.')

        if not contents:
            self.add_error('contents', '내용을 입력해주세요.')

blog_page/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from django.views import View
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from .forms import BlogForm
from .models import Blog
from user.models import User
from tag.models import Tag
from followers.models import Followers
from user.decorators import login_required
# Create your views here.



class HomePage(View):
    def get(self, request):

        return render(request,'homepage.html', {'username': request.session.get('user')})

class IndexView(View):
    def get(self, request):
        blogs = Blog.objects.all().order_by('-id')
        page = int(request.GET.get('p', 1))
        paginator = Paginator(blogs, 4)

        blogs = paginator.get_page(page)
        return render(request, 'index.html', {'username': request.session.get('user'), 'blogs':blogs})

class FollowerBlogView(View):
    def get(self, request):
        username = request.session.get('user')
        if username == None:
            blogs = []
        else:
            user = User.objects.get(username=username)
            followee, _ = Followers.objects.get_or_create(follower=user)
            followee = followee.followee.all()
            blogs = Blog.objects.filter(writer__in=followee).all().order_by('-id')
            page = int(request.GET.get('p', 1))
            paginator = Paginator(blogs, 4)

            blogs = paginator.get_page(page)
        return render(request, 'follower_blogs.html',{'username': request.session.get('user'), 'blogs':blogs})

@method_decorator(login_required, name='dispatch')
class MyBlogList(ListView):
    template_name = 'my_blog.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.session.get('user')
        return context

    def get_queryset(self, **kwargs):
        queryset = Blog.objects.filter(writer__username=self.request.session.get('user')).order_by('-id')
        return queryset

class BlogList(View):
    def get(self, request, writer=None):
        username = request.session.get('user')
        if writer == username:
            return redirect('/myblog/')
        blogs = Blog.objects.filter(writer__username=writer)
        followee = []
        if username != None:
            user = User.objects.get(username=username)
            followee, _ = Followers.objects.get_or_create(follower=user)
            followee = list(followee.followee.values('username'))
            follow_bool = {'username':writer} in followee
        else:
            follow_bool = False
        return render(request, 'other_blog.html',  {'username': username,'blogs':blogs,'writer':writer,'follow_bool':follow_bool})



class RelationCreateView(View):
    def post(self, request):
        username = request.session.get('user')

        if username == None:
            return JsonResponse({'result': 'fail'})
        writer = request.POST.get('followee',None)

        if writer == None:

            return JsonResponse({'result': 'fail'})
        writer = User.objects.get(username=writer)
        tt = request.POST.get('tt',None)
        if tt == '0':
            user = User.objects.get(username=username)
            followee, _ = Followers.objects.get_or_create(follower=user)
            followee.followee.add(writer)
            followee.save()
        elif tt == '1':
            user = User.objects.get(username=username)
            followee, _ = Followers.objects.get_or_create(follower=user)
            followee.followee.remove(writer)
            followee.save()
        return JsonResponse({'result':"success"})

class BlogDetail(DetailView):
    template_name = "blog_detail.html"
    queryset = Blog.objects.all()
    context_object_name = "blog"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.session.get('user')
        return context


@method_decorator(login_required, name='dispatch')
class BlogWrite(FormView):
    template_name = 'blog_write.html'
    form_class = BlogForm
    success_url = 'myblog/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.session.get('user')
        return context

    def form_valid(self, form):

        print(self.request.FILES.get('image','blank.png'))
        user = User.objects.get(username=self.request.session.get('user'))
        blog = Blog(
            title=form.data.get('title'),
            contents=form.data.get('contents'),
            thumbnails=self.request.FILES.get('image','blank.png'),
            writer=user,
        )
        blog.save()
        tags = form.data.get('tags').split(',')
        for tag in tags:
            if not tag:
                continue
            _tag, _ = Tag.objects.get_or_create(name=tag)
            blog.tags.add(_tag)

        return super().form_valid(form)

blog_page/templates/base.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  {% block header %}
  {% endblock %}
</head>

<body>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
          <span>{{ message }}</span>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                  </svg>
          </button>
      </div>
    {% endfor %}
  {% endif %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" herf="/">Django Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="/">Home</a>
        <a class="nav-item nav-link" href="/myblog">My Blog</a>
        {% if username != None %}
        <a class="nav-item nav-link" href="/logout/">Logout</a>
        {% else %}
        <a class="nav-item nav-link" href="/login/">Login</a>
        {% endif %}

      </div>
    </div>
  </nav>
  {% block homepage %}
  {% endblock %}
  <div class="container">
    {% block contents %}
    {% endblock %}
  </div>
</body>

</html>

blog_page/templates/blog_detail.html
{% extends "base.html" %}
{% load humanize %}
{% block contents %}
<div class="row mt-5">
    <div class="col-12">
        <div class="form-group">
            <label class="mt-1" for="title">제목</label>
            <div class="form-control" id="title"/>
            <p>{{ blog.title }}</p>
            </div>
            <label class="mt-1" for="contents">내용</label>
            <div id="contents" class="border" style="min-height:300px;">
                {{ blog.contents|safe }}
            </div>

            <label class="mt-1" for="tags">태그</label>
            <div id="tags" class="d-flex flex-row">
            {% for tag in blog.tags.all %}
            <a class="alert alert-primary mx-1">{{ tag.name }}</a>
            {% endfor %}
            </div>
        </div>
        <button class="btn btn-primary" onclick="location.href='/myblog/'">돌아기기</button>
    </div>
</div>
{% endblock %}

blog_page/templates/blog_write.html
{% extends 'base.html' %}

{% block header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
<script>
    $(document).ready(function (){
        $('#id_contents').summernote({
            height: 400
        });
    });

    $(function(){
        $('#id_image').change(function(){
            if(this.files[0]){
                var reader = new FileReader();
                reader.readAsDataURL(this.files[0]);
                reader.onload = function(e) {
                  $('#image-preview').attr('src', e.target.result);
                  $('#image-preview').attr('width', '180');
                  $('#image-preview').attr('height', '180');
                };
            }
        })
    })
</script>
{% endblock %}
{% block contents %}
<div class="row mt-3">
    <div class="col-12 text-center">
        <h1>블로그 등록하기</h1>
    </div>
</div>
<div>
    <div class="row mt-3">
        <div class="col-12">
            {{ error }}
        </div>
    </div>
</div>
<div class="row mt-3">
    <div class="col-12">
        <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% if field.name == 'contents' %}
                <textarea class="form-control" name="{{ field.name }}" id="{{ field.id_for_label }}"></textarea>
                {% elif field.name == 'image' %}
                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}"/>
                <image id="image-preview" />
                {% else %}
                <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}"/>
                {% endif %}
            </div>
            {% if field.erros %}
            <span style="color:red">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary">등록</button>

        </form>
        <button class="btn btn-primary" onclick="location.href='/myblog/'">돌아가기</button>
    </div>
</div>
{% endblock %}

blog_page/templates/follower_blogs.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  {% block header %}
  {% endblock %}
</head>


<body>
    <div class="container">
    {% for blog in blogs %}
        <div class="row mt-1 border">
                {% if blog.thumbnails != None %}
                <img src="{{ blog.thumbnails.url }}" class="col-3">
                {% else %}
                <img class="col-3">
                {% endif %}
                <div class="col-5">
                    <div class="my-1"><a href='/blog/detail/{{ blog.id }}' target="_top">{{ blog.title }}</a></div>
                    <div class="my-1">{{ blog.contents|safe|slice:":20" }}...</div>
                    <div id="tags" class="d-flex flex-row">
                    {% for tag in blog.tags.all %}
                    <span class="badge badge-secondary mx-1">{{ tag.name }}</span>
                    {% endfor %}
                    </div>
                </div>
                <div class="col-1 font-weight-bold font-italic">
                    <a id="blog-writer-{{ blog.id }}" href="/myblog/{{ blog.writer }}/" target="_top">{{ blog.writer }}</a>
                </div>
                <div class="col-3">{{ blog.registered_date }}</div>
        </div>

    {% empty %}
    <div><h1>No Contents</h1></div>
    {% endfor %}
    <div class="row mt-2">
            <div class="col-12">
                <nav>
                    <ul class="pagination justify-content-center">
                        {% if blogs.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{ blogs.previous_page_number }}">이전으로</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">이전으로</a>
                        </li>
                        {% endif %}

                        <li class="page-item active">
                            <a class="page-link" href="#">{{ blogs.number }} / {{ blogs.paginator.num_pages }}</a>
                        </li>

                        {% if blogs.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{ blogs.next_page_number }}"> 다음으로</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">다음으로</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</body>
</html>

blog_page/templates/homepage.html
{% extends 'base.html' %}

{% block homepage %}
<ul class="nav nav-tabs">
  <li class="nav-item" style="width:50%;">
    <a class="nav-link active" data-toggle="tab" href="#qwe">최근 글들</a>
  </li>
  <li class="nav-item" style="width:50%;">
    <a class="nav-link" data-toggle="tab" href="#asd">팔로우한 사용자들의 글</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade show active" id="qwe">
    <iframe src="/recent-blog/" style="width:100%;height:90vh"></iframe>
  </div>
  <div class="tab-pane fade" id="asd">
    <iframe src="/blog/follower/" style="width:100%;height:90vh"></iframe>
  </div>
</div>
{% endblock %}

blog_page/templates/index.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  {% block header %}
  {% endblock %}
</head>

<body>
    <div class="container">
    {% for blog in blogs %}
        <div class="row mt-1 border">
                {% if blog.thumbnails != None %}
                <img src="{{ blog.thumbnails.url }}" class="col-3">
                {% else %}
                <img class="col-3">
                {% endif %}
                <div class="col-5">
                    <div class="my-1"><a href='/blog/detail/{{ blog.id }}' target="_top">{{ blog.title }}</a></div>
                    <div class="my-1">{{ blog.contents|safe|slice:":20" }}...</div>
                    <div id="tags" class="d-flex flex-row">
                    {% for tag in blog.tags.all %}
                    <span class="badge badge-secondary mx-1">{{ tag.name }}</span>
                    {% endfor %}
                    </div>
                </div>
                <div class="col-1 font-weight-bold font-italic">
                    <a id="blog-writer-{{ blog.id }}" href="/myblog/{{ blog.writer }}/" target="_top">{{ blog.writer }}</a>
                </div>
                <div class="col-3">{{ blog.registered_date }}</div>
        </div>
    {% endfor %}
        <div class="row mt-2">
            <div class="col-12">
                <nav>
                    <ul class="pagination justify-content-center">
                        {% if blogs.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{ blogs.previous_page_number }}">이전으로</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">이전으로</a>
                        </li>
                        {% endif %}

                        <li class="page-item active">
                            <a class="page-link" href="#">{{ blogs.number }} / {{ blogs.paginator.num_pages }}</a>
                        </li>

                        {% if blogs.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?p={{ blogs.next_page_number }}"> 다음으로</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">다음으로</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</body>
</html>

blog_page/templates/my_blog.html
{% extends 'base.html' %}
{% load humanize %}
{% block contents %}

<div class="row mt-3">
    <div class="col-12 text-center">
        <h1>내가 쓴 글들</h1>
    </div>
</div>
<div class="row mt-1">
    <div class="col-11"></div>
    <div class="col-1">
        <button class="btn btn-sm btn-primary" onclick="location.href='/blog/write/'">글쓰기</button>
    </div>
</div>
{% for blog in page_obj %}
<div class="row mt-1 border">
        <img src="{{ blog.thumbnails.url }}" class="col-3">
        <div class="col-6">
            <div class="my-1"><a href='/blog/detail/{{ blog.id }}'>{{ blog.title }}</a></div>
            <div class="my-1">{{ blog.contents|safe|truncatewords:30 }}</div>
            <div id="tags" class="d-flex flex-row">
            {% for tag in blog.tags.all %}
            <span class="badge badge-secondary mx-1">{{ tag.name }}</span>
            {% endfor %}
            </div>
        </div>
        <div class="col-3">{{ blog.registered_date }}</div>
</div>
{% endfor %}
<div class="row mt-2">
    <div class="col-12">
        <nav>
         <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전으로</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">이전으로</a>
            </li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="#">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</a>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}"> 다음으로</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">다음으로</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

blog_page/templates/other_blog.html
{% extends 'base.html' %}
{% load humanize %}
{% block header %}
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $( function() {

        jQuery.jQueryAlert = function (msg) {
         var $messageBox = $.parseHTML('<div id="alertBox"></div>');
         $("body").append($messageBox);

         $($messageBox).dialog({
             open: $($messageBox).append(msg),
             title: "결과",
             autoOpen: true,
             modal: true,
             buttons: {
                 OK: function () {
                     $(this).dialog("close");
                 }
             }
         });
         }
    });
    function follow(tt){
        $.ajax({
            type: 'POST',
            url: '/follow/',
            data: {'followee':'{{ writer }}','tt':tt},
            success: function(response){
                if(response['result'] == 'success'){
                    window.location.reload();
                }
                else if(response['result'] == 'fail'){
                    console.log('1111');
                    location.href = '/login';
                }
            }
        });
    }
</script>
{% endblock %}
{% block contents %}

<div class="row mt-3">
    <div class="col-12 text-center">
        <h1>{{ writer }}가 쓴 글들</h1>
    </div>
</div>
<div class="row mt-1">
    <div class="col-10"></div>
    <div class="col-1" id="follow-div">
        {% if follow_bool %}
        <button class="btn btn-sm btn-primary" onclick="follow(1)">UnFollow</button>
        {% else %}
        <button class="btn btn-sm btn-primary" onclick="follow(0)">Follow</button>
        {% endif %}
    </div>
    <div class="col-1">
        <button class="btn btn-sm btn-primary" onclick="location.href='/blog/write/'">글쓰기</button>
    </div>
</div>
{% csrf_token %}
{% for blog in blogs %}
<div class="row mt-1 border">
        <img src="{{ blog.thumbnails.url }}" class="col-3">
        <div class="col-6">
            <div class="my-1"><a href='/blog/detail/{{ blog.id }}'>{{ blog.title }}</a></div>
            <div class="my-1">{{ blog.contents|safe|truncatewords:30 }}</div>
            <div id="tags" class="d-flex flex-row">
            {% for tag in blog.tags.all %}
            <span class="badge badge-secondary mx-1">{{ tag.name }}</span>
            {% endfor %}
            </div>
        </div>
        <div class="col-3">{{ blog.registered_date }}</div>
</div>
{% endfor %}
{% endblock %}